config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  post 'search', to: 'search#search', as: 'search'
  get 'my_trails', to: 'trails#my_trails', as: 'my_trails'

  resources :trails do
    resources :followers, only: [:create]
    resources :video_contents, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end

  resources :video_contents, only:[:show,:destroy]
  resources :meetings, only: :index
  resources :followers, only: [:destroy]

  resources :meetings, only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      get "weekly"
      get "monthly"
    end
  end
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :trail
  belongs_to :user
  validates :start_time, :end_time, presence: true
  default_scope -> { order(:start_time) }


  def time
    "#{start_time.strftime('%I:%M %p')} - #{end_time.strftime('%I:%M %p')}"

  end
  def multi_days?
   (end_time.to_date - start_time.to_date).to_i >= 1
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
before_action  :authenticate_user!
before_action :set_trails,only: [:index,:new,:show,:edit,:update]


def index
  @start_date = params.fetch(:start_date, Date.today).to_date
    @meetings = Meeting.where(start_time: @start_date.beginning_of_week..@start_date.end_of_week,user: current_user)
    if @meetings.empty?

      @meetings = Meeting.where(end_time: @start_date.beginning_of_week..@start_date.end_of_week,user: current_user)
    end

end

def weekly
  @start_date = params.fetch(:start_date, Date.today).to_date
    @meetings = Meeting.where(start_time: @start_date.beginning_of_week..@start_date.end_of_week,user: current_user)
    if @meetings.empty?

      @meetings = Meeting.where(end_time: @start_date.beginning_of_week..@start_date.end_of_week,user: current_user)
    end

end


def monthly
  @start_date = params.fetch(:start_date, Date.today).to_date
    @meetings = Meeting.where(start_time: @start_date.beginning_of_month..@start_date.end_of_month,user: current_user)
    if @meetings.empty?

      @meetings = Meeting.where(end_time: @start_date.beginning_of_month..@start_date.end_of_month,user: current_user)
    end

end



  def new
    @meeting = Meeting.new
  end




def create
  @meeting = Meeting.new(meeting_params)
  @meeting.user = current_user
  if @meeting.save
    redirect_to monthly_meetings_path, notice: "You have a new routine booked!"
  else
    flash.now[:alert] = 'Please try again!'
    render :new
  end
end


  def show
    @meeting = Meeting.find(params[:id])
  end

  def edit
    @meeting = Meeting.find(params[:id])
  end

  def update
    @meeting = Meeting.find(params[:id])
    if @meeting.update(meeting_params)
      redirect_to monthly_meetings_path
    else
      render :edit
    end
  end


  def destroy
    @meeting = Meeting.find(params[:id])
    @meeting.destroy
    redirect_to monthly_meetings_path, notice: 'Routine deleted!'
  end


  #def index
    # Scope your query to the dates being shown:
   # @start_date = params.fetch(:start_date, Date.today).to_date
    #@start_date = (Date.today).to_date

    # For a monthly view:
   # @meetings = Meeting.where(start_time: start_date.beginning_of_month.beginning_of_week..start_date.end_of_month.end_of_week)

    # Or, for a weekly view:
     # @meetings = Meeting.where(start_time: @start_date.beginning_of_week..@start_date.end_of_week)

  #end
private

def set_trails
  @trails = Trail.where(user:current_user)
end

def meeting_params
  params.require(:meeting).permit(:trail_id,:start_time,:end_time)
end
end

app/views/meetings/_form.html.erb
<div class="container-forms d-flex justify-content-center mt-2">

  <%= simple_form_for @meeting do |f| %>
  <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <%= f.input :start_time, as: :string, label: "Select an start date and time", input_html:{ data: { controller: 'flatpickr' } } %>
    <%= f.input :end_time, as: :string, label: "Select an end date and time", input_html: { data: { controller: 'flatpickr' }} %>
    <%= f.input :trail_id, collection: @trails, value_method: :id, label: "Select one of your Trails do book into this routine:" ,include_blank: false %>
    <%= f.submit 'Book your routine', class: 'btn btn-info' %>
    <% end %>
  </div>


  <% if meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meeting.errors.count, "error") %> This Trails cannot be booked:</h2>
      <ul>
        <% meeting.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if @meeting.persisted? %>
    <%#= link_to 'Delete routine', meeting_path(@meeting),  method: :delete, data: { turbo_method: "delete",confirm: 'Are you sure?' } %>
  <% end %>
</div>

app/views/meetings/_meeting.html.erb
<%= month_calendar(events: @meetings, end_attribute: :end_time) do |date, meetings| %>
  <%= date %>

  <% meetings.each do |meeting| %>
    <div class="meeting">  <-- We will add some style to the meeting class later so let's add it now -->
      <p><%= meeting.name %></p>
    </div>
  <% end %>
<% end %>
<form data-controller="flatpickr">
  <label for="start_time">Start Time:</label>
  <input type="text" name="start_time" id="start_time" data-flatpickr-target="startTime">

  <label for="end_time">End Time:</label>
  <input type="text" name="end_time" id="end_time" data-flatpickr-target="endTime">
</form>

app/views/meetings/_month_calendar.html.erb
<div class="container-routine">
  <%= month_calendar(events: @meetings, end_attribute: :end_time) do |date, meetings| %>
      <%= date.to_formatted_s(:short) %>

      <% meetings.each do |meeting| %>
        <div class="meeting">
          <p><%= link_to meeting.trail.title, trail_path(meeting.trail) %></p>
          <%= link_to meeting_path(meeting),method: :delete, data:{turbo_method:"delete"} do  %>
          <i class="fa-solid fa-trash"></i>
          <%end %>
          <%= link_to edit_meeting_path(meeting), method: :get, title: "Edit routine" do %>
          <i class="fa-solid fa-pencil"></i>
          <%end %>
          <small><%= meeting.time unless meeting.multi_days? %></small>
        </div>
      <% end %>
    <% end %>
</div>

app/views/meetings/_week_calendar.html.erb
<div class="container-routine">
  <%= week_calendar(events: @meetings, end_attribute: :end_time) do |date, meetings| %>
      <%= date.to_formatted_s(:short) %>

      <% meetings.each do |meeting| %>
        <div class="meeting">
          <p><%= link_to meeting.trail.title, trail_path(meeting.trail) %></p>
          <%= link_to meeting_path(meeting),method: :delete, data:{turbo_method:"delete"} do  %>
          <i class="fa-solid fa-trash"></i>
          <%end %>
          <%= link_to edit_meeting_path(meeting), method: :get, title: "Edit routine" do %>
          <i class="fa-solid fa-pencil"></i>
          <%end %>
          <small><%= meeting.time unless meeting.multi_days? %></small>
        </div>
      <% end %>
    <% end %>
</div>

app/views/meetings/edit.html.erb
<div class="container-forms d-flex justify-content-center text-center mt-2">
  <div class="row">
    <h3>Editing your routine<h3>
    <p id="landing-info"> Feel free to update you routine!</p>
  </div>
</div>
<div class="container-forms d-flex justify-content-center mt-2">
    <%= render 'form', meeting: @meeting %>
</div>
<div class="d-flex justify-content-center mt-2">
  <div class="container-forms d-flex justify-content-center mt-2">
    <%= link_to 'Go back!', meetings_path, class: 'btn btn-primary mx-3' %>    <%= link_to 'Delete routine', meeting_path(@meeting), class: "btn btn-danger",  method: :delete, data: { turbo_method: "delete",confirm: 'Are you sure?' } %>
  </div>
</div>

app/views/meetings/index.html.erb
<div class="container-forms d-flex justify-content-center text-center mt-4">
  <div class="row">
    <h3>Pick up a free time to start a learning journey!<h3>
    <p id="landing-info">Discipline and constancy are crucial to build up new habits.</p>
    <p id="landing-info">And to help you in this path, create as much routines you need to seize the most of your Trails!</p>
  </div>
</div>

<div class="container-forms d-flex justify-content-center">
  <%@meetings.count %>
  <%= link_to "Create new routine",new_meeting_path,class: "btn btn-primary" %>
</div>

<div class="calendar-container">
  <div>
    <%=render "meetings/month_calendar" %>
  </div>
</div>

app/views/meetings/monthly.html.erb
<div class="container-forms d-flex justify-content-center text-center mt-4">
  <div class="row">
    <h3>Pick up a free time to start a learning journey!<h3>
    <p id="landing-info">Discipline and constancy are crucial to build up new habits.</p>
    <p id="landing-info">And to help you in this path, create as much routines you need to seize the most of your Trails!</p>
  </div>
</div>

<div class="container-forms d-flex justify-content-center">
  <%@meetings.count %>
  <%= link_to "Create new routine",new_meeting_path,class: "btn btn-primary" %>
</div>

<div class="calendar-container" style="height:80vh">
  <%=render "meetings/month_calendar" %>
</div>

app/views/meetings/new.html.erb
<div class="container-forms d-flex justify-content-center text-center mt-4">
  <div class="row">
    <h3>Creating a new routine<h3>
    <p id="landing-info">Fill up the form bellow to book one of your Trails in your calendar!</p3>
  </div>
</div>

<% unless @trails.present? %>
    <h3>You don't have any Trails yet ):</h3>
    <%= link_to "Create new Trail", new_trail_path, class: "btn btn-info" %>
    <%else %>
<%= render 'form', meeting: @meeting %>
<%end %>

<div class="container-forms d-flex justify-content-center text-center mt-5">
  <%= link_to 'Go back!', meetings_path, class: 'btn btn-primary' %>
</div>

<%= flash[:alert] if flash[:alert].present? %>

app/views/meetings/show.html.erb
<h1>Routine details</h1>


<p><strong>Trail:</strong> <%= @meeting.trail.name %></p>
<p><strong>Start time:</strong> <%= @meeting.start_time %></p>
<p><strong>End time:</strong> <%= @meeting.end_time %></p>


<%= link_to 'Edit routine', edit_meeting_path(@meeting) %>

<%= link_to 'Delete routine', meeting_path(@meeting),
            method: :delete,
            data: { confirm: 'Are you sure?' } %>

app/views/meetings/weekly.html.erb
<div class="container-forms d-flex justify-content-center text-center mt-4">
  <div class="row">
    <h3>Pick up a free time to start a learning journey!<h3>
    <p id="landing-info">Discipline and constancy are crucial to build up new habits.</p>
    <p id="landing-info">And to help you in this path, create as much routines you need to seize the most of your Trails!</p>
  </div>
</div>

<div class="container-forms d-flex justify-content-center">
  <%@meetings.count %>
  <%= link_to "Create new routine",new_meeting_path,class: "btn btn-primary" %>
</div>

<div class="calendar-container" style="height:80vh">
  <%=render "meetings/week_calendar" %>
</div>