config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  post 'search', to: 'search#search', as: 'search'
  get 'my_trails', to: 'trails#my_trails', as: 'my_trails'

  resources :trails do
    resources :followers, only: [:create]
    resources :video_contents, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end

  resources :video_contents, only:[:show,:destroy]
  resources :meetings, only: :index
  resources :followers, only: [:destroy]

  resources :meetings, only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      get "weekly"
      get "monthly"
    end
  end
end

app/models/trail.rb
class Trail < ApplicationRecord
  belongs_to :user
  has_many :video_contents, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :meetings, dependent: :destroy
  has_one_attached :photo
  CATEGORIES = ["Culture", "Entertainment", "Fashion", "Gastronomy", "Music", "Nature", "Phylosophy", "Self-Care", "Sports", "Technology", "Others"]
  validates :category, presence: true, inclusion: { in: CATEGORIES.map { |category| category.capitalize }}
end

app/controllers/trails_controller.rb
class TrailsController < ApplicationController
  # before_action :set_trail, only: %i[ show edit update destroy ]
  # skip_after_action :verify_authorized

  def index
    if params[:filter].present?
      @trails = Trail.where(category: params[:filter].capitalize)
    else
      @trails = Trail.all
    end
    # authorize @trails
  end

  def my_trails
    @trails = current_user.trails
  end

  def copy
    original_trail = Trail.find(params[:id])
    new_trail = original_trail.dup
    new_trail.user = current_user
    new_trail.save

    redirect_to trail_path(new_trail)
  end

  def show
    @trail = Trail.find(params[:id])
    @average = @trail.reviews.empty? ? 0 : @trail.reviews.pluck(:rating).reduce(:+) / @trail.reviews.count
    @video_content = VideoContent.new
    # authorize @trail
  end

  def new
    @trail = Trail.new
    # authorize @trail
  end

  def create
    @trail = Trail.new(trail_params)
    @trail.user = current_user
    # authorize @trail
    if @trail.save
      redirect_to edit_trail_path(@trail), notice: "Trail created successfully"
    else
      render :new
    end
  end

  def edit
    @trail = Trail.find(params[:id])
    # authorize @trail
  end

  def update
    # authorize @trail
    @trail = Trail.find(params[:id])
    if @trail.update(trail_params)
      redirect_to trail_path(@trail), notice: "Trail updated successfully"
    else
      render :edit
    end
  end

  def destroy
    # authorize @trail
    @trail = Trail.find(params[:id])
    @trail.destroy

    redirect_to trails_path, status: :see_other, notice: "Trail deleted successfully"
  end

  def search
    @results = YoutubeService.new.search_videos(params[:query])
  end

  private

  def trail_params
    params.require(:trail).permit(:title, :description, :category, :photo)
  end
end

app/views/trails/_form.html.erb
<div class="container-forms d-flex justify-content-center mt-5">

  <%= simple_form_for(@trail) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :photo, as: :file, label: "Pick up an image as your Trail's cover" %>
      <%= f.input :title, label: "Insert your Trail's title:"  %>
      <%= f.input :description, label: "You can also define a description to your Trail:" %>
      <%= f.input :category, label: "Which category better fits with your Trail content?", collection: Trail::CATEGORIES.map { |category| category.capitalize } %>
    </div>

    <div class="form-actions row d-flex justify-content-between">
      <div class="col text-center">
      <%= link_to "Go back!", @trail, class: "btn btn-primary" %>
      </div>
      <div class="col text-center">
      <%= f.button :submit, class: "btn btn-success" %>
      </div>
    </div>
  <% end %>

</div>

app/views/trails/_search_content.html.erb
<div class='my-search-form mb-5 mx-auto mt-3 w-75' data-controller="youtube-search" data-youtube-search-trail-value="<%= @trail.id %>">
  <%= form_with( html: {data:{ action: "submit->youtube-search#search"}, class: " d-flex mb-3"}) do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "What do you wanna learn today?",
      data: { "youtube-search-target" => "query"}
    %>
    <%= submit_tag "Search!", class: "btn btn-primary" %>
  <% end %>
  <div data-youtube-search-target="container results cards">
    <%= link_to "Refresh your search bar", edit_trail_path(@trail.id), class: "btn btn-secondary", data: {"youtube-search-target": "clearResults"}, hidden: true %>
  </div>
</div>
<% if @results.present? %>
  <ul>
    <% @results.each do |result| %>
      <li>
        <a href="https://www.youtube.com/watch?v=<%= result['id']['videoId'] %>" target="_blank">
          <%= result['snippet']['title'] %>
        </a>
      </li>
    <% end %>
  </ul>
<% else %>
<% end %>

app/views/trails/_trail.html.erb
<div class="container">
  <div class="row">
    <%= render "trails/search_content", locals:{trail: @trail} %>
    <% if @results.present? %>
      <%@results.each do |video| %>
      <%= render "trails/video", locals:{video: video} %>
      <%end %>
    <% end %>
  </div>
</div>


        <div>
          <% if current_user.id == @trail.user_id %>
            <div class="btn btn-success video-content-btn">
              <%= link_to "See Video","https://www.youtube.com/watch?v=#{video.video_id}", class: "vertical-text", target: "_blank" %></h3>
            </div>
          <% else %>
        </div>
<div class="row col-6">
  <div class="cards" id="cards-show">
    <div class="card" id="card-show">
    <% if trail.photo.attached? %>
      <img class="card-img-top" src="<%= cl_image_path trail.photo.key, crop: :fill %>" alt="Card image cap">
      <%end %>
      <div class="content">
        <h3 class="card-title"><strong><%=trail.title%></strong></h3>
        <p class="card-text"><%=trail.description%></p>
      </div>
    </div>
  </div>
</div>
<div class="row col-6">
  <div class="cards">
    <% trail.video_contents.each do |video| %>
      <div class="card" id="card-video">
        <img class="card-img-top" src="<%= video.thumb_url %>" alt="">
        <h3><%=video.title %> <%= link_to "see video","https://www.youtube.com/watch?v=#{video.video_id}", target: "_blank" %></h3>
        <%#= button_to "Destroy this video", video_content_path(video), method: :delete, data: {turbo: false, confirm: "Are you sure?"} %>
        <%= button_to "Delete Video", video_content_path(video), method: :delete, remote: true, data: {turbo: false, confirm: "Are you sure?", "turbo-confirm": "Are you sure?", "turbo-method": "delete", "controller": "video-content" } %>
        <br>
      </div>
    <% end %>
  </div>
</div>

app/views/trails/_video.html.erb
<% results.each do |video| %>
  <div class="card mb-3 mt-3">
    <img src="<%= video[:snippet][:thumbnail][:standard]%>" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title"><%= video[:snippet][:title] %></h5>
      <p class="card-text"><%= video[:snippet][:description] %>.</p>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
      <br>
    </div>
  </div>
<% end %>

app/views/trails/edit.html.erb
<div class="container-forms d-flex justify-content-center mt-4">
  <div class="row text-center">
    <h2>This is your Trail about <strong>"<%= @trail.title %>"</strong></h2>
    <p id="landing-about"> Here you can edit your Trail's info, use the search bar bellow to include more videos and also delete those one you don't like anymore.</p>
  </div>
</div>

<div class="container-forms row">
    <div class="col-6 p-1">
      <%= render "form", trail: @trail %>
      <%#= button_to "Delete Trail", @trail, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger remove-btn" if @trail.id %>
    </div>
    <div class="col-6 p-4">
      <div class="cards">
        <% @trail.video_contents.each do |video| %>
          <div class="mb-3">
            <%= link_to "https://www.youtube.com/watch?v=#{video.video_id}", target: "_blank", class: "" do %>
              <div class="d-flex card-show my-1 mx-auto">
                <div class="card-img" id="img-video-show">
                  <img src="<%= video.thumb_url %>" alt="Image description">
                </div>
                <div class="card-content">
                  <div class="card-title">
                    <p id="title-video-show"><%= video.title %></p>
                  </div>
                </div>
              </div>
            <% end %>
              <% if current_user.id == @trail.user_id %>
                <div class="d-flex justify-content-end">
                  <%= link_to video_content_path(video), class: "trash-icon", remote: true, data: {turbo_confirm: "Are you sure?", turbo_method: :delete, "controller": "video-content" } do %>
                    <i class="fa-solid fa-trash"></i>
                  <% end %>
                </div>
              <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="container d-flex mx-auto">
  <%= render "trails/search_content", locals:{trail: @trail} %>
  <% if @results.present? %>
    <%@results.each do |video| %>
    <%= render "trails/video", locals:{video: video} %>
    <%end %>
  <% end %>
</div>

app/views/trails/index.html.erb
<div class="container text-center font-weight-bold">
 <div class="hero">
    <% if current_user.trails.any? %>
      <h3><strong>Welcome <%= (current_user.first_name&.capitalize) %> <%= (current_user.last_name&.capitalize) %>!</strong></h3>
      <p id="landing-about">Now you can create a new Trail.</p>
      <%= link_to "Create Trail", new_trail_path, class: "btn btn-primary mb-3" %>
      <p id="landing-about">Or enjoy the available Trails bellow:</p>
    <% else %>
      <h3><strong>Welcome <%= (current_user.first_name).capitalize %> <%= (current_user.last_name).capitalize %>!</strong></h3>
      <p id="landing-about">Seems like you don't have any Trail yet. To create one just click in the buttom bellow.</p>
      <%= link_to "Create Trail", new_trail_path, class: "btn btn-primary mb-3" %>
      <p id="landing-about">Or enjoy the available Trails bellow:</p>
    <% end %>
  </div>
</div>
<div class="container">
  <div class="cards" id="cards-index">
    <% @trails.each do |trail| %>
      <%= link_to trail_path(trail) do %>
        <div class="card">
          <% if trail.photo.attached? %>
          <%= cl_image_tag trail.photo.key, crop: :fill, class: "card-img-top" %>
          <% else %>
          <%= image_tag "trail-photo-default.JPG", class: "card-img-top" %>
          <% end %>
          <div class="content">
            <h3 class="card-title"><strong><%= trail.title %></strong></h3>
            <p class="card-text"><%= trail.description %></p>
            <p class="card-text"><%= trail.category %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/trails/my_trails.html.erb
<div class="container d-flex justify-content-center text-center mt-5">
  <div class="row">
    <h3><strong><%= (current_user.first_name&.capitalize) %> <%= (current_user.last_name&.capitalize) %>, here you can se all your Trails.</strong></h3>
    <p id="landing-about">You can enjoy it all and also create another one!</p>
  </div>
</div>
<div class="container d-flex justify-content-center text-center">
  <div class="row">
    <%= link_to "Create Trail", new_trail_path, class: "btn btn-primary" %>
  </div>
</div>

<div class="container">
  <%# <div class=""> %>
    <div class="cards" id="cards-index">
      <% @trails.each do |trail| %>
        <%= link_to trail_path(trail) do %>
          <div class="card">
            <% if trail.photo.attached? %>
            <%= cl_image_tag trail.photo.key, crop: :fill, class: "card-img-top" %>
            <% else %>
            <%= image_tag "trail-photo-default.JPG", class: "card-img-top" %>
            <% end %>
            <div class="content">
              <h3 class="card-title"><strong><%=trail.title%></strong></h3>
              <p class="card-text"><%=trail.description%></p>
              <p class="card-text"><%= trail.category %></p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  <%# </div> %>
</div>
<%# <%= link_to "New trail", new_trail_path %>

app/views/trails/new.html.erb
<div class="container-forms d-flex justify-content-center mt-5">
  <div class="row">
    <h3>It's time to create your most amazing Trail!</strong></h3>
  </div>
</div>

<%= render "form", trail: @trail %>

<br>

<div>

  <%#= link_to "Back to My Trails", trails_path %>

</div>

app/views/trails/show.html.erb
<div class="container show-trails mt-3">
  <div class="cards" id="cards-show">
    <div class="card" id="card-show" >
      <% if @trail.photo.attached? %>
        <%= cl_image_tag @trail.photo.key, crop: :fill, class: "card-img-top" %>
        <% else %>
        <%= image_tag "trail-photo-default.JPG", class: "card-img-top" %>
      <% end %>
      <div class="content">
        <h3 class="card-title"><strong><%= @trail.title %></strong></h3>
        <p class="card-text"><%= @trail.description %></p>
        <p class="card-text"><%= @trail.category %></p>
      </div>
    </div>
  </div>
</div>
<div class="cards">
  <% @trail.video_contents.each do |video| %>
    <div class="mb-3 w-75 mx-auto">
      <%= link_to "https://www.youtube.com/watch?v=#{video.video_id}", target: "_blank", class: "mx-0" do %>
        <div class="d-flex card-show">
          <div class="card-img" id="img-video-show">
            <img src="<%= video.thumb_url %>" alt="Image description">
          </div>
          <div class="card-content">
            <div class="card-title">
              <p id="title-video-show"><%= video.title %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>
<div class="buttons d-flex justify-content-center">
  <%# if policy(@trail).edit? %>
    <% if current_user.id == @trail.user_id  %>
    <div>
      <%= link_to "Go back!", trails_path, class: "btn btn-primary" %>
    </div>
    <div>
      <%= link_to "Edit Trail", edit_trail_path(@trail), class: "btn btn-success mx-5" %>
    </div>
        <%= button_to "Delete Trail", @trail, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger remove-btn" if @trail.id %>
    <% else %>
    <div>

      <%= link_to "Go back!", trails_path, class: "btn btn-primary" %>
      <%#= button_to "Seguir Trilha", followers_path(@trail), method: :post %>
    </div>
    <% end %>
  <%# end %>
</div>