config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  post 'search', to: 'search#search', as: 'search'
  get 'my_trails', to: 'trails#my_trails', as: 'my_trails'

  resources :trails do
    resources :followers, only: [:create]
    resources :video_contents, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end

  resources :video_contents, only:[:show,:destroy]
  resources :meetings, only: :index
  resources :followers, only: [:destroy]

  resources :meetings, only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      get "weekly"
      get "monthly"
    end
  end
end

app/models/video_content.rb
class VideoContent < ApplicationRecord
  belongs_to :trail
  # validates :video_id, uniqueness: true
end

app/controllers/video_contents_controller.rb
class VideoContentsController < ApplicationController
  before_action :set_video_content, only: [:show, :edit, :update, :destroy]
#  skip_after_action :verify_authorized

  def index
    @video_contents = VideoContent.all
  end

  def show
  end

  def new
    @video_content = VideoContent.new
  end

  def edit
  end

  def create
    @video_content = VideoContent.new(video_content_params)
    @video_content.trail = Trail.find(params[:trail_id])
    respond_to do |format|
      if @video_content.save
        format.html { redirect_to @video_content, notice: 'o conteudo do video foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @video_content }
      else
        format.html { render :new }
        format.json { render json: @video_content.errors.messages, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @video_content.update(video_content_params)
        format.html { redirect_to @video_content, notice: 'O conteudo do video foi atualizado com sucesso' }
        format.json { render :show, status: :ok, location: @video_content }
      else
        format.html { render :edit }
        format.json { render json: @video_content.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @video_content.destroy
    respond_to do |format|
      format.html { redirect_to edit_trail_path(@video_content.trail), notice: 'O conteudo do video foi excluido com sucesso' }
      format.json { head :no_content }
    end
  end

  private

  def set_video_content
    @video_content = VideoContent.find(params[:id])
  end

  def video_content_params
    params.require(:video_content).permit(:video_id, :title, :thumb_url, :trail_id, :description)
  end
end

app/views/video_contents/_form.html.erb
<%= form_for @video_content do |f| %>
  <% if @video_content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video_content.errors.count, "error") %></h2>

      <ul>
      <% @video_content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :video_id %>
    <%= f.text_field :%>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :thumb_url %>
    <%= f.text_field :thumb_url %>
  </div>

  <div class="field">
    <%= f.label :trail_id %>
    <%= f.text_field :trail_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/video_contents/_video_content.html.erb
<p>
  <strong>Video ID:</strong>
  <%= @video_content.video_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @video_content.title %>
</p>

<p>
  <strong>Thumbnail URL:</strong>
  <%= @video_content.thumb_url %>
</p>

<p>
  <strong>Trail ID:</strong>
  <%= @video_content.trail_id %>
</p>

<%= link_to 'Edit', edit_video_content_path(@video_content) %> |

<%= link_to 'Go back!', video_contents_path %>

app/views/video_contents/edit.html.erb
<h1>Edit Video Content</h1>

<%= render 'form', video_content: @video_content %>

<%= link_to 'Show', @video_content %> |

<%= link_to 'Go back!', video_contents_path %>

app/views/video_contents/index.html.erb
<h1>Video Contents</h1>

<!DOCTYPE html>
<html>
  <head>
    <title>My Trails</title>
  </head>


<table>
  <thead>
    <tr>
      <th>Video ID</th>
      <th>Title</th>
      <th>Thumbnail URL</th>
      <th>Trail ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @video_contents.each do |video_content| %>
      <tr>
        <td><%= video_content.video_id %></td>
        <td><%= video_content.title %></td>
        <td><%= video_content.thumb_url %></td>
        <td><%= video_content.trail_id %></td>
        <td><%= link_to 'Show', video_content %></td>
        <td><%= link_to 'Edit', edit_video_content_path(video_content) %></td>
        <td><%= link_to 'Delete', video_content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video Content', new_video_content_path %>

app/views/video_contents/new.html.erb
<h1>New Video Content</h1>

<%= render 'form', video_content: @video_content %>

<br>

<%= link_to 'Go back!', video_contents_path %>

app/views/video_contents/show.html.erb
<p>
  <strong>Video ID:</strong>
  <%= @video_content.video_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @video_content.title %>
</p>

<p>
  <strong>Thumbnail URL:</strong>
  <%= @video_content.thumb_url %>
</p>

<p>
  <strong>Trail ID:</strong>
  <%= @video_content.trail_id %>
</p>

<br>

<%= link_to 'Edit', edit_video_content_path(@video_content) %> |
<%= link_to 'Back', video_contents_path %>